// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package users

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID
	CreatedAt    sql.NullTime
	Username     string
	PasswordHash string
}
